Show severity in Github Workflow command message
ansible/ansible-lint pull request #1055
Opened 2020-09-14 15:29 UTC by JiriSko

Fixes: #1054

2020-09-14 16:43 UTC, ssbarnea commented on lib/ansiblelint/formatters/__init__.py
> +            f"::[E{rule_id}] [{severity}] {violation_details}"
Based on how the format looks, what you want is to add `,severity={}` on the first line and avoid polluting the message itself.

2020-09-14 18:36 UTC, rafaelfolco reviewed
This worked for me only when I specify
ansible-lint --parseable-severity roles/test.yml 

When I use -p (pep8 format), the severity info is gone.
Is this expected ?

2020-09-15 10:34 UTC, ssbarnea requested changes
Please convert it to draft until you pass all tests.

2020-09-17 07:38 UTC, ssbarnea commented
Code looks ok now but before merging it, do you have a proof it does work? My guess is that github should just ignore the message but it could also prevent it from rendering them. 

Can you please made a manual test of producing such an annotation and confirm that it works?

The second question would, what if github does not display severity at all in the UI. How is this feature going to help the user?

I am quite curious about you use-case around priority as I never seen it more than something put inside the rule documentation.

2020-10-05 09:04 UTC, ssbarnea commented
@JiriSko If you cannot produce an example that proves that github actions would not choke when receiving an additional parameter and that it is possible to view the severity on the annotations produced I will have to close this PR.

Even a screenshot is enough. You should be able to test this with a simple print that produces an annotation that is using this format.

The only reason I am asking this is because I want to prevent a potential break in current code by merging this feature without confirmation that it works.

2020-10-05 15:51 UTC, JiriSko commented
Sorry it took so long. Here's test with old and new annotation format:
https://github.com/codeacio/ansible-lint/actions/runs/289711321

2020-10-05 16:18 UTC, ssbarnea commented
@jimi-c No worries. Now we know that github accepts extra data in severity. Still, my impression is that the severity will not be visible to the user. How is user going to make use of it?

2020-10-05 16:22 UTC, JiriSko commented
It's part of my CI to categorize issues to errors and warnings. Isn't visible directly in Github. I'm using it in previous version of ansible-lint.

2020-10-05 17:36 UTC, ssbarnea approved these changes

2020-10-05 17:36 UTC, merged