Git output to follow verbosity setting
ansible/ansible-lint pull request #2369
Opened 2022-08-31 01:51 UTC by kostyaplis

This is to have an ability to suspend `git` output in progressive mode.
As currently it doesn't allow to retrieve pure json output

It preserves the current behaviour if `quiet` is not set.

[Test repo](https://github.com/kostyaplis/ansible-lint-test)

Latest master:
```console
$ ansible-lint --progressive -f json -q -q playbook-test1.yml

Preparing worktree (checking out 'old-rev')
HEAD is now at f17ba41 Second commit. Fix 1 violation
[{"type": "issue", "check_name": "name[play]", "categories": ["idiom"], "severity": "major", "description": "All plays should be named.", "fingerprint": "8f4941934aab4dc5115f825d0e2227bb38b1b6d82f2e32d636f856c8319a7393", "location": {"path": "playbook-test1.yml", "lines": {"begin": 1}}}, {"type": "issue", "check_name": "command-instead-of-shell", "categories": ["command-shell", "idiom"], "severity": "critical", "description": "Use shell only when shell functionality is required.", "fingerprint": "b2c4318aaf4e587a5aab71607f1409cb9ed455b38d8b91efaefd5c1b39a2df4d", "location": {"path": "playbook-test1.yml", "lines": {"begin": 3}}, "content": {"body": "Task/Handler: test"}}, {"type": "issue", "check_name": "name[casing]", "categories": ["idiom"], "severity": "major", "description": "All names should start with an uppercase letter.", "fingerprint": "51e7dd5782d4115dece8ddde17bde707ec1f35ae35a0bfffae812b0f84c2e08d", "location": {"path": "playbook-test1.yml", "lines": {"begin": 3}}, "content": {"body": "Task/Handler: test"}}, {"type": "issue", "check_name": "no-changed-when", "categories": ["command-shell", "idempotency"], "severity": "critical", "description": "Commands should not change things if nothing needs doing.", "fingerprint": "4c865dced7f2cc06a89fb0cb8124bde9f89f62a762c9e7472474989079490b54", "location": {"path": "playbook-test1.yml", "lines": {"begin": 3}}, "content": {"body": "Task/Handler: test"}}]
```

Fix applied:
```console
$ ansible-lint --progressive -f json -q -q playbook-test1.yml

[{"type": "issue", "check_name": "name[play]", "categories": ["idiom"], "severity": "major", "description": "All plays should be named.", "fingerprint": "8f4941934aab4dc5115f825d0e2227bb38b1b6d82f2e32d636f856c8319a7393", "location": {"path": "playbook-test1.yml", "lines": {"begin": 1}}}, {"type": "issue", "check_name": "command-instead-of-shell", "categories": ["command-shell", "idiom"], "severity": "critical", "description": "Use shell only when shell functionality is required.", "fingerprint": "b2c4318aaf4e587a5aab71607f1409cb9ed455b38d8b91efaefd5c1b39a2df4d", "location": {"path": "playbook-test1.yml", "lines": {"begin": 3}}, "content": {"body": "Task/Handler: test"}}, {"type": "issue", "check_name": "name[casing]", "categories": ["idiom"], "severity": "major", "description": "All names should start with an uppercase letter.", "fingerprint": "51e7dd5782d4115dece8ddde17bde707ec1f35ae35a0bfffae812b0f84c2e08d", "location": {"path": "playbook-test1.yml", "lines": {"begin": 3}}, "content": {"body": "Task/Handler: test"}}, {"type": "issue", "check_name": "no-changed-when", "categories": ["command-shell", "idempotency"], "severity": "critical", "description": "Commands should not change things if nothing needs doing.", "fingerprint": "4c865dced7f2cc06a89fb0cb8124bde9f89f62a762c9e7472474989079490b54", "location": {"path": "playbook-test1.yml", "lines": {"begin": 3}}, "content": {"body": "Task/Handler: test"}}]
```

2022-08-31 01:59 UTC, kostyaplis commented
Note that `stderr=subprocess.DEVNULL` deliberately left hardcoded for `git worktree add` subprocess.
As it produces `fatal: '/Users/konstantinplis/.cache/ansible-compat/f23de3/old-rev' already exists` output when cache dir exists. More confusing than helpful.

2022-08-31 08:28 UTC, ssbarnea requested changes
The fix is right but we must include test update to prevent regression. We already had too many regression related to progressive mode just because we have no test on it.

I would suggest creating a single test_progressive which would do the following:

- use [tmp_path](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html) to work on an empty folder
- git init
- add first commit with one playbook
- add second commit with a change, maybe another file to lint?
- run `ansible-lint -vv --progressive` on it
- check output of ansible lint
- check if json output is valid

Can you do that? That will likely have prevented at least 3 issues I seen recently.

2022-09-06 03:58 UTC, kostyaplis commented
@ssbarnea please review. thanks!

2022-09-09 11:42 UTC, kostyaplis commented
Following changes implemented:
1. Cleanup `worktree_dir` on each `_previous_revision()` run. Otherwise it doesn't work with `tmp_path` in `test_progressive.py`. Each subsequent test run on local machine will try to create a new worktree and fails if it exists.
2. Completely silence git subprocess output. Otherwise it generates amount of not useful output. Log previous commit SHA, as it might be useful for debugging.
3. Add progressive mode test

Please review, do let me know if any changes required. Thanks!

2022-09-12 14:27 UTC, ssbarnea approved these changes

2022-09-12 14:28 UTC, merged