Add win_command/win_shell to no-free-form modules
ansible/ansible-lint pull request #2596
Opened 2022-10-12 15:18 UTC by nre-ableton

https://github.com/ansible/ansible-lint/pull/2586 softened the `no-free-form` rule, but unfortunately missed the Windows equivalents for these modules.

2022-10-12 20:08 UTC, ssbarnea requested changes
Good point!

Can you also add the FQCN of these to the list ansible.windows. for windows ones and ansible.builtin. for the old ones, so we cover for all forms.

2022-10-13 07:36 UTC, nre-ableton commented
@ssbarnea Great point! Does it look better now?

2022-10-13 09:49 UTC, ssbarnea approved these changes

2022-10-13 09:50 UTC, merged

2022-10-13 09:59 UTC, nre-ableton commented
@ssbarnea Thanks for the quick merge. :+1: