Allow prefix in combination with task name
ansible/ansible-lint pull request #2740
Opened 2022-11-25 10:44 UTC by shatakshiiii

2022-11-25 20:25 UTC, ssbarnea commented on src/ansiblelint/rules/name.py
> +            if prefix_name == "main":
You also need to check if the prefix is matching allowed pattern. I would suggest to take a different approach and build the expected prefix based on prefix template string. If it does not match we can raise an error with tag `name[prefix]` and a clear message.

This also means that you can easily check if filename base name (w/o extension) is main and make the expected prefix = "".

You will be able to generate an error message like "Task name should use `<foo>` prefix in order to make it easy to identify.

2022-11-25 20:25 UTC, ssbarnea requested changes
see comment

2022-12-02 15:27 UTC, ssbarnea approved these changes

2022-12-02 15:48 UTC, cidrblock approved these changes
+1 for _collection and the test coverage looks good

2022-12-02 16:22 UTC, merged