Added tests for text.py
ansible/ansible-lint pull request #2902
Opened 2023-01-17 15:35 UTC by ajinkyau

Signed-off-by: Ajinkya Udgirkar <audgirka@redhat.com>

2023-01-17 16:23 UTC, ssbarnea requested changes
While in good direction, it shill does not increase coverage of the two lines we needed to cover.

You need to pass a bytes object to do this, not a string.

For the second one, you want to pass some data that would force it to raise and Error, as that was the execution path that was not covered.

2023-01-18 09:47 UTC, ssbarnea requested changes

2023-01-18 09:47 UTC, ssbarnea commented on test/test_text.py
> +        assert isinstance(err, RuntimeError)
Please use pytest.raises instead

2023-01-18 10:51 UTC, ajinkyau commented on test/test_text.py
> +        assert isinstance(err, RuntimeError)
done

2023-01-18 11:12 UTC, ssbarnea approved these changes

2023-01-18 11:12 UTC, merged