count no of tasks rule
ansible/ansible-lint pull request #3156
Opened 2023-03-09 06:47 UTC by Ruchip16

2023-03-09 10:48 UTC, ssbarnea requested changes
@Ruchip16 Please be sure that you address all the linting problems, `tox -e lint` should pass before the effective review starts.

2023-03-09 10:48 UTC, Ruchip16 commented
> @Ruchip16 Please be sure that you address all the linting problems, `tox -e lint` should pass before the effective review starts.

sure, i will keep in mind

2023-03-09 11:02 UTC, ssbarnea requested changes
- [ ] Add a complexity.md file with documentation about rule
- [ ] Create a symlink from docs/rules/complexity.md -> the one in source code
- [ ] Add tests inside complexity.py file like in other rules (pytest)
- [x] Update description field
- [x] Update version_added and make it "v6.15.0"
- [x] Update tags to include "experimental" and "idiom"

There should be two test files named:
- `examples/playbooks/rule-complexity-pass.yml`
- `examples/playbooks/rule-complexity-fail.yml`

2023-04-19 13:49 UTC, ssbarnea approved these changes

2023-04-19 17:48 UTC, ssbarnea commented
I tried to get this in and uncovered a longer chain of issues, so I am moving it draft until I do the preparatory work to get it in.

2023-06-14 14:44 UTC, ssbarnea commented
Yes, please.

2023-06-22 11:56 UTC, ssbarnea commented on .vscode/settings.json
Do not touch this file as part of this change.

2023-06-23 10:52 UTC, ssbarnea approved these changes

2023-06-23 10:52 UTC, merged