Limit the maximum block depth
ansible/ansible-lint pull request #3602
Opened 2023-07-04 11:01 UTC by Ruchip16

Since inside tasks there can be nested blocks so this PR limits the depth of the block by a certain limit which helps to maintain the readability of the playbooks.

fixes: #2173

2023-07-06 11:44 UTC, ajinkyau requested changes

2023-07-06 11:44 UTC, ajinkyau commented on examples/playbooks/rule-complexity-fail.yml
> +        - name: Nested Task 20
@Ruchip16 we need one more task added here and it should fail as the limit is 20 tasks

2023-07-06 11:44 UTC, ajinkyau commented on examples/playbooks/rule-complexity-fail.yml
> +        - name: Nested Task 20
This change should result in 2 failures for this playbook on line:
https://github.com/ansible/ansible-lint/pull/3602/files#diff-8e317bdeb6fb7d81373aa20796059598fecdb9c8c50255d1edbc5d1d946d7a3aR91

2023-07-06 11:54 UTC, ajinkyau commented on src/ansiblelint/rules/complexity.py
> +        if task.get("action") == "block":
@Ruchip16 This condition will not return true as `task.get("action")` returns a dict instead of a string

2023-08-21 17:38 UTC, ssbarnea commented
> hey @ssbarnea @ajinkyau can you review this please?

Please check the last commit and see all the extra changes I had to do there. The original code was not really working and the tests were failing to check for the behavior. Still, it was not too hard to fix.

2023-08-21 17:51 UTC, cidrblock approved these changes

2023-08-21 17:52 UTC, Ruchip16 commented
> > hey @ssbarnea @ajinkyau can you review this please?
> 
> Please check the last commit and see all the extra changes I had to do there. The original code was not really working and the tests were failing to check for the behavior. Still, it was not too hard to fix.

the main thing i got wrong and really confused was with the example of the block, i although discussed that once with ajinkya, but nevertheless, apologies for the extra work and would contribute more to get a good hang of it!

2023-08-21 17:52 UTC, merged

2023-08-28 10:29 UTC, bluikko commented
Does this PR really limit maximum block depth, or tasks inside a block?

There seems to be a conflict between the PR name and the help files contained in the PR diff:
- PR name talks about "block depth", i.e. nested blocks.
- PR diff contains 2 new rule description items which only talk about number of tasks inside block.

Please clarify which one it is, something is wrong here.

2023-08-28 10:47 UTC, Ruchip16 commented
`limit maximum block` depth means that it limits the depth of any block (nested or not) up to a certain number which is currently 20 by default, if the tasks inside a block are > 20 it would raise a warning message, so maximum block depth refers to the depth of the block and nesting is a scenario inside that, hope that clears your confusion

2023-08-28 12:13 UTC, bluikko commented
> `limit maximum block` depth means that it limits the depth of any block

It does not, at all. It strengthens my opinion that the words are misused here.  
"Depth" refers to how many nested layers there are in my opinion.