Allow dashes in namespaces
ansible/ansible-lint pull request #3962
Opened 2023-12-28 12:16 UTC by sur5r

2023-12-29 17:35 UTC, ssbarnea commented
Can you please also update the link to documentation to a valid page that documents the new namespace requirements?

2023-12-29 17:36 UTC, ssbarnea requested changes
This might not be enough to allow dashes in namespaces but we can probably add some tests ourselfs. Still, before this, please include links to documentation that includes the new namespace requirements as we do not want to just rely on "current behavior".

2023-12-29 18:11 UTC, sur5r commented
Unfortunately, I have no idea where this is documented.

I have to admit that I have spent way too many hours fighting windmills around this galaxy vs. galaxy-ng vs. namespaces vs. legacy namespaces vs. dash-to-underscore-to-dash-to-dot-conversion disaster.

I fully understand if you don't want to merge this without proper docs and or tests, but I'm completely lost here.

2024-01-11 14:20 UTC, ssbarnea approved these changes

2024-01-11 14:20 UTC, merged