Support examples for role entrypoints
ansible/ansible-lint pull request #4019
Opened 2024-02-10 13:51 UTC by felixfontein

Ref: https://github.com/ansible/ansible/pull/82671
Ref: https://github.com/ansible/ansible/issues/81734

2024-02-12 14:06 UTC, ssbarnea approved these changes

2024-02-12 14:07 UTC, ssbarnea requested changes
Blocked until core changes are merged.

2024-05-01 19:12 UTC, felixfontein commented
Marking as ready for review since https://github.com/ansible/ansible/pull/82671 has been merged.

2024-05-02 12:08 UTC, ssbarnea approved these changes

2024-05-02 12:09 UTC, merged

2024-05-02 12:22 UTC, felixfontein commented
@ssbarnea @audgirka thanks!