GitHub Action: avoid extra working directory prefix for wget
ansible/ansible-lint pull request #4232
Opened 2024-06-26 14:24 UTC by ptoscano

The whole shell step for wget is run with the working directory for the action; hence, drop the extra prefix to the --output-document parameter of the wget command.

2024-06-26 14:39 UTC, richm commented
we fixed this in system roles by using an absolute path for the working directory (for ansible-lint and ansible-test also) - https://github.com/linux-system-roles/kernel_settings/pull/206

2024-06-27 08:01 UTC, bkaraoren reviewed
When you run this on a container it was not getting the correct `working-directory` from GITHUB environment variables. GITHUB environment variables are only available for the RUNNER, not on a container in RUNNER. Please check the previous requirements by the changes.

2024-06-27 08:09 UTC, ptoscano commented
@bkaraoren I think you misunderstand what this PR does: the shell `run` block used to invoke `wget` already has the `working_directory` parameter set, so using it _again_ in the output filename of `wget` is not correct.

What you describe sounds like a problem in the detection of the default working directory in case the `working_directory` parameter of this action is not specified (see the first set of the action, currently labelled "Process inputs"). In that case, I think that automatic detection ought to be fixed.

2024-07-02 08:15 UTC, bkaraoren commented
> tection ought to be fixe

@ptoscano yep, that sounds also good. without providing any directory such as `${{ steps.inputs.outputs.working_directory }}` I also expect it to work but former commit needs to be checked why it has been reverted back from not using any working directory in the commit #3938. Could be useful to check it to understand the reason what was the reason to include.

2024-07-31 11:50 UTC, ssbarnea requested changes
Based on given reviews, I think that is better not to touch it unless the change is also adding tests, especially for called via container approach. Without this, we will probably close the PRs.

2024-09-11 22:10 UTC, tigattack commented
We're going in circles here; this PR brings us back to the same state as before #4103.

For myself and others using a GitHub action in a repository subdirectory, #4103 addressed a major issue (see #3938, now #4323). However, it also introduced problems for other users.

In response, #4213 was merged, but this caused the action to become unusable again without resorting to hacky workarounds for the same use case.

Instead of continuing in this cycle, we should take a step back and reevaluate the approach, as each "fix" solves one group's problem but introduces a new breaking bug for another.

2024-09-19 14:23 UTC, ssbarnea commented
@tigattack @bkaraoren @ptoscano Please check https://github.com/ansible/ansible-lint/pull/4340 which will fix this issue while also adding regression tests. Once merged this PR will be closed. I will release it later today, hopefully addressing these long standing issues.

2024-09-19 14:40 UTC, closed without merging